[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Adding the specific version path in remappings helps the IDE find the files
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]
